<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>OrgaNICE</title>';
echo '<link rel="stylesheet" href="css/main.css">';
echo '</head>';
echo '<body>';
echo '<div class="navbar">';
echo '<div class="container">';
echo '<a class="logo" href="#">Orga<span>NICE!</span></a>';
echo '';
echo '<nav>';
echo '<ul class="primary-nav">';
echo '<li class="current"><a href="#">Home</a></li>';
echo '<li><a href="#feat">Features</a></li>';
echo '<li><a href="#">Pricing</a></li>';
echo '<li><a href="#cont">Contact</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '';
echo '<section class="hero">';
echo '';
echo '<div class="container">';
echo '';
echo '<div class="left-col">';
echo '<p class="subhead">List it all &amp; I'll be your one-time call</p>';
echo '<h1>Let's Manage Your Life</h1>';
echo '';
echo '<div class="hero-cta">';
echo '<a href="#" class="primary-cta">Manage Now</a>';
echo '</div>';
echo '</div>';
echo '<img src="images/messy2.png" class="hero-img" alt="illustration">';
echo '</div>';
echo '</section>';
echo '<footer>';
echo '<div class="container">';
echo '<h1></h1>';
echo '</div>';
echo '</footer>';
echo '';
echo '</body>';
echo '</html>';
?>